// What themes/tebin/theme.json is made of, in one place.
//
// The script that writes the file and the test that proves the file was not
// hand-edited both call this. They used to each spell the input list out for
// themselves, which is precisely the drift the test exists to catch, running
// inside the test: a change to the generator's inputs left the test asserting
// against the old recipe, and the test failed for a reason that had nothing
// to do with anybody editing the file.

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { buildTheme, readTokens, themeJson } from './generate.js';
import { rasteriseSvg } from './rasterise.js';

/**
 * The mark's raster height. It prints at 24pt, so this is roughly 15x the
 * printed size — enough that Word can scale it without softening, small
 * enough to keep the theme file readable.
 */
export const CORNER_MARK_PX = 512;

/** The generated theme, as the exact JSON text that belongs on disk. */
export async function tebinThemeJson(brandDir: string): Promise<string> {
  const [dtcg, logoSvg, logoPng, cornerMarkSvg] = await Promise.all([
    readFile(join(brandDir, 'tokens.dtcg.json'), 'utf8'),
    readFile(join(brandDir, 'logo-full.svg'), 'utf8'),
    readFile(join(brandDir, 'logo-full.png')),
    readFile(join(brandDir, 'corner-mark.svg'), 'utf8'),
  ]);

  // The corner mark's raster is derived from its own vector, not vendored
  // beside it. It used to be both, and the two disagreed: the vendored PNG's
  // canvas was 256x260 while its ink stopped at y=203, so Word printed a mark
  // whose vertical bar fell short of the corner while the PDF's reached it.
  // Nothing could catch that — a vendored binary is not anybody's output, it
  // is a file somebody put there. One source of truth removes the
  // disagreement instead of testing for it.
  const cornerMarkPng = await rasteriseSvg(cornerMarkSvg, CORNER_MARK_PX);

  return themeJson(
    buildTheme({
      tokens: readTokens(dtcg),
      // buildTheme normalises the SVG's own line endings before embedding it,
      // so this checkout's line endings (LF here, thanks to .gitattributes;
      // CRLF on a checkout that lacks one, a zip export, or a different
      // editor) do not leak into the generated bytes.
      logoSvg,
      logoPngBase64: logoPng.toString('base64'),
      cornerMarkSvg,
      cornerMarkPngBase64: cornerMarkPng.toString('base64'),
      sourceId: 'tebin-classic',
      sourceVersion: '1.0.0',
    }),
  );
}
